'use strict';
// The renderer's behaviour contract: ordinary markdown renders as it always
// did, and hostile markdown cannot become script.
//
// Everything here drives renderMarkdown itself, not a unit of the parser. The
// defects this suite exists for all live in the pre- and post-processing
// wrapped around marked, so a test that called marked directly would exercise
// none of them.
//
// The first group matters most day to day: the likeliest way to fail at this is
// to break ordinary markdown while closing the hole. formatMd has nine call
// sites across chat and message handling, so a regression there is visible in
// every conversation in the app.
const { test, describe } = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');
const { JSDOM } = require('jsdom');
const { makeRenderer, loadBrowserMarked, attachWikilinkHandler, attachCodeCopyHandler } = require('../helpers/markdown-harness.js');
const { createMarkdownRenderer } = require('../../public/markdown-render.js');

const FIXTURES = path.join(__dirname, '..', 'fixtures');
const BENIGN_MD = fs.readFileSync(path.join(FIXTURES, 'markdown-benign.md'), 'utf8');
// What this renderer produces now. Regenerated only by a commit that means to
// change rendering, and never without the invariant below still holding.
const BENIGN_HTML = fs.readFileSync(path.join(FIXTURES, 'markdown-benign.html'), 'utf8');
// What the renderer produced on main BEFORE this change, generated from the code
// in public/app.js as it stood. Frozen: nothing on this branch may regenerate
// it, because it is the only record of what "unchanged" means.
const BENIGN_BEFORE = fs.readFileSync(path.join(FIXTURES, 'markdown-benign-before.html'), 'utf8');

const { renderMarkdown } = makeRenderer();
const render = (src) => renderMarkdown(src, { callouts: true });

// The shape of a rendered document: every element, its class, and its own
// text, exactly.
//
// This is the invariant that must hold across every commit here. The byte
// fixture is stricter and legitimately moves, because this work turns two
// inline handlers into listeners and drops the blank line the old callout box
// left behind it. This does not move. If the escaping work ever swallows an
// element, changes a class, or alters a single character INSIDE one, it fails,
// and regenerating the byte fixture cannot hide it.
//
// Text is compared per element rather than as one string for the whole
// document, so whitespace BETWEEN block elements is out of scope while
// whitespace inside them, which is the whole content of a <pre>, is compared
// exactly. The container's own text nodes are the only thing skipped, and at
// the top level of marked's output those are the inter-block newlines.
// The two attributes this change deliberately moves, and the ONLY two the
// comparison is allowed to ignore. Everything else, href, src, alt, title,
// type, checked, style, class, is compared exactly, so losing one fails here
// rather than only in the byte fixture, which is regenerated by design whenever
// rendering changes and so cannot be the thing that catches a loss.
const MIGRATED_ATTRIBUTES = new Set(['onclick', 'data-wikilink']);

function outline(html) {
  const dom = new JSDOM(`<div id="root">${html}</div>`);
  const ownText = (el) => Array.from(el.childNodes)
    .filter((node) => node.nodeType === 3)
    .map((node) => node.data)
    .join('');
  const attributes = (el) => Array.from(el.attributes)
    .filter((a) => !MIGRATED_ATTRIBUTES.has(a.name))
    .map((a) => `${a.name}=${a.value}`)
    .sort();
  const walk = (el) => Array.from(el.children).map((child) => ({
    tag: child.tagName.toLowerCase(),
    attrs: attributes(child),
    text: ownText(child),
    children: walk(child),
  }));
  return walk(dom.window.document.getElementById('root'));
}

describe('renderMarkdown: ordinary markdown is untouched by this change', () => {
  // The fixture's PROVENANCE is checked by `npm run check:fixture`, not from
  // here. It reproduces the file from the pre-change public/app.js read out of
  // git history, and this suite must not depend on git history: CI checks out
  // at depth 1, so the base commit does not exist in the clone and the check
  // could only ever fail there or be skipped into meaninglessness. It runs in
  // the pre-commit gate and in the CI job that checks out full history.

  test('the benign document renders to the recorded bytes', () => {
    assert.strictEqual(render(BENIGN_MD), BENIGN_HTML);
  });

  test('the benign document keeps the structure and text it had before this change', () => {
    assert.deepStrictEqual(outline(render(BENIGN_MD)), outline(BENIGN_BEFORE));
  });

  test('code blocks, tables, task lists and callouts still render', () => {
    // Counted against the pre-change output rather than against a number typed
    // here, so widening the fixture cannot leave this asserting the old shape.
    const doc = new JSDOM(`<div id="root">${render(BENIGN_MD)}</div>`).window.document;
    const was = new JSDOM(`<div id="root">${BENIGN_BEFORE}</div>`).window.document;
    const same = (selector, what) => assert.strictEqual(
      doc.querySelectorAll(selector).length, was.querySelectorAll(selector).length, what);

    same('.code-block-wrapper pre code.hljs', 'fenced blocks');
    same('.md-table-wrap > table > thead', 'wrapped tables');
    same('input[type="checkbox"]', 'task list items, tight and loose');
    same('input[checked]', 'ticked items');
    same('.callout.callout-note', 'callouts');
    same('a.wikilink', 'wikilinks and rewritten workspace links');
    same('img', 'images');
    same('.md-tag', 'tags');
    same('li > p', 'loose list item paragraphs');

    assert.ok(doc.querySelectorAll('input[type="checkbox"]').length >= 4,
      'the fixture carries both a tight and a loose task list');
    const callout = doc.querySelector('.callout.callout-note');
    assert.strictEqual(callout.querySelector('.callout-title').textContent, 'Plain title');
    assert.ok(callout.querySelector('.callout-content strong'), 'callout body is still parsed as markdown');
  });

  test('highlighting still applies to fenced code', () => {
    const doc = new JSDOM(`<div id="root">${render(BENIGN_MD)}</div>`).window.document;
    const js = doc.querySelector('.code-block-wrapper');
    assert.strictEqual(js.querySelector('.code-lang').textContent, 'JavaScript');
    assert.ok(js.querySelector('code.hljs .hljs-keyword'), 'hljs token spans are present');
  });
});

// ---------------------------------------------------------------------------
// Injection point 3: wikilink source rewriting.
//
// Before this change, renderMarkdown replaced [[target|label]] in the SOURCE with
//   <a class="wikilink" onclick="openWikilink('$1')">$2</a>
// and took both captures verbatim. `$1` lands inside a single-quoted JavaScript
// string inside a double-quoted HTML attribute, so a quote in the target ends
// the string and everything after it is code the page runs on click; a quote
// plus a space opens a NEW attribute, and onmouseover does not even need the
// click. Recorded payloads, run against the previous renderer:
//   [[note' onmouseover='alert(1)]]
//     -> onclick="openWikilink('note' onmouseover='alert(1)')"
//   [[a') + alert(1) + ('b]]
//     -> onclick="openWikilink('a') + alert(1) + ('b')"
// ---------------------------------------------------------------------------
describe('renderMarkdown: wikilink targets cannot reach the handler as code', () => {
  const attrs = (html) => {
    const doc = new JSDOM(`<div id="root">${html}</div>`).window.document;
    return Array.from(doc.querySelectorAll('*')).flatMap((el) => Array.from(el.attributes).map((a) => a.name));
  };

  test('a quote in a wikilink target cannot open a second attribute', () => {
    // Both quote characters, because the target now travels in a double-quoted
    // attribute and only the double quote can end that one. The single-quote
    // payload is the one the old inline handler fell to and is kept as the
    // record of it.
    for (const src of ["[[note' onmouseover='alert(1)]]", '[[note" onmouseover="alert(1)]]']) {
      const html = render(src);
      assert.ok(!attrs(html).some((name) => name.startsWith('on')), `handler attribute survived: ${html}`);
    }
  });

  test('a wikilink target that closes the call cannot append an expression', () => {
    const payload = "a') + alert(1) + ('b";
    const d = new JSDOM(`<div id="root">${render(`[[${payload}]]`)}</div>`).window.document;
    const anchor = d.querySelector('a.wikilink');
    // The payload reaches the page as one attribute VALUE and reads back
    // through the DOM as the characters it was written with. Before, the same
    // text was an expression the page evaluated on click.
    assert.strictEqual(anchor.getAttribute('data-wikilink'), payload);
    assert.deepStrictEqual(
      Array.from(anchor.attributes).map((a) => a.name).filter((n) => n.startsWith('on')), []);
  });

  test('no wikilink render carries an event-handler attribute', () => {
    for (const src of ['[[Plain]]', '[[Target|Label]]', "[[a'b]]", '[[a"b]]', '[[a\\b]]']) {
      assert.ok(!attrs(render(src)).some((name) => name.startsWith('on')), `handler attribute in: ${src}`);
    }
  });

  test('a click still reaches the opener with the same target value', () => {
    // The target values the old onclick would have passed, for targets that did
    // not break it. The listener must deliver these characters unchanged.
    const targets = ['Plain note', 'folder/Note', "Bobby's note", 'a"b', 'a\\b', "note' onmouseover='alert(1)"];
    for (const target of targets) {
      const dom = new JSDOM('<div id="root"></div>', { url: 'http://localhost/' });
      const doc = dom.window.document;
      doc.getElementById('root').innerHTML = render(`[[${target}]]`);
      const seen = [];
      attachWikilinkHandler(doc, (value) => seen.push(value));
      const anchor = doc.querySelector('a.wikilink');
      assert.ok(anchor, `no anchor for target: ${target}`);
      anchor.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true }));
      assert.deepStrictEqual(seen, [target]);
    }
  });

  test('the visible label is still the alias, or the target when there is none', () => {
    const doc = (html) => new JSDOM(`<div id="root">${html}</div>`).window.document;
    assert.strictEqual(doc(render('[[Target|Label]]')).querySelector('a.wikilink').textContent, 'Label');
    assert.strictEqual(doc(render('[[Target]]')).querySelector('a.wikilink').textContent, 'Target');
    assert.ok(doc(render('[[Target|**bold**]]')).querySelector('a.wikilink strong'), 'alias is still parsed as markdown');
  });

  test('a wikilink inside code is left alone, which the source rewrite could not do', () => {
    // Recorded change of behaviour, not a regression. The old pass ran a
    // regex over the whole source, so `[[a]]` inside a code span became the
    // literal text of an anchor tag. A tokenizer never enters a code span.
    const html = render('`[[a]]`');
    assert.ok(/<code>\[\[a\]\]<\/code>/.test(html), html);
  });
});

// ---------------------------------------------------------------------------
// Injection point 2: callout titles.
//
// processCalloutsSrc built its box by string concatenation BEFORE any parser
// ran: `<div class="callout-title">${title}</div>`, where title is the raw
// remainder of the `> [!type]` line. marked was never involved, so nothing
// about the parser's own escaping applied. Recorded payload, run against the
// previous renderer:
//   > [!note] <img src=x onerror=alert(1)>
//     -> <div class="callout-title"><img src=x onerror=alert(1)></div>
// which is an image element in the DOM with an onerror handler, and needs no
// interaction at all: a broken src fires it on render.
// ---------------------------------------------------------------------------
describe('renderMarkdown: a callout title is text, not markup', () => {
  const doc = (html) => new JSDOM(`<div id="root">${html}</div>`).window.document;

  test('a callout title containing a tag renders as text', () => {
    const d = doc(render('> [!note] <img src=x onerror=alert(1)>\n> body\n'));
    assert.strictEqual(d.querySelectorAll('img').length, 0, 'no element was created from the title');
    assert.strictEqual(d.querySelector('.callout-title').textContent, '<img src=x onerror=alert(1)>');
  });

  test('a callout title cannot close the box it is written into', () => {
    const d = doc(render('> [!note] </div><a href="#" onclick="alert(1)">x</a><div>\n> body\n'));
    assert.strictEqual(d.querySelectorAll('a').length, 0);
    assert.strictEqual(d.querySelectorAll('.callout-title').length, 1);
    assert.ok(d.querySelector('.callout-content'), 'the box still has its content div');
  });

  test('no callout render carries an event-handler attribute', () => {
    for (const src of [
      '> [!note] <img src=x onerror=alert(1)>\n> body\n',
      '> [!tip] " onmouseover="alert(1)\n> body\n',
    ]) {
      const d = doc(render(src));
      const names = Array.from(d.querySelectorAll('*')).flatMap((el) => Array.from(el.attributes).map((a) => a.name));
      assert.ok(!names.some((n) => n.startsWith('on')), `handler attribute in: ${src}`);
    }
  });

  test('the callout type still becomes the modifier class', () => {
    const d = doc(render('> [!Warning] Careful\n> body\n'));
    assert.ok(d.querySelector('.callout.callout-warning'), 'type is lowercased into the class');
  });
});

// ---------------------------------------------------------------------------
// Injection point 4: relative-link rewriting.
//
// A link whose href ended in .md/.yaml/.yml/.json/.txt was rewritten, AFTER
// marked had produced HTML, into an inline handler:
//   `onclick="openWikilink('${href.replace(/'/g, "\\'")}')"`
// The escaping is a JavaScript rule applied to a value going into an HTML
// attribute, and an HTML attribute is not a JavaScript string until the browser
// has finished parsing it: character references are decoded FIRST, and the
// replace never sees them. Recorded payload, run against the previous renderer:
//   [a](<&#39;&#41;;alert&#40;1&#41;;//.md>)
//     -> onclick="openWikilink('&#39;&#41;;alert&#40;1&#41;;//.md')"
// which the parser decodes to
//        openWikilink('');alert(1);//.md')
// and the page runs alert(1) on click. Backslashes cannot do it, because marked
// percent-encodes them in an href; character references walk straight past.
// ---------------------------------------------------------------------------
describe('renderMarkdown: a relative link cannot rewrite its own handler', () => {
  const handlerAttrs = (html) => {
    const d = new JSDOM(`<div id="root">${html}</div>`).window.document;
    return Array.from(d.querySelectorAll('*')).flatMap((el) => Array.from(el.attributes))
      .filter((a) => a.name.startsWith('on'));
  };

  test('character references in a filename cannot become code', () => {
    const html = render('[a](<&#39;&#41;;alert&#40;1&#41;;//.md>)');
    assert.deepStrictEqual(handlerAttrs(html).map((a) => a.name), [], html);
  });

  test('a quote or a backslash in a filename cannot alter the handler', () => {
    for (const src of ["[a](<x'.md>)", '[a](<x\\\\.md>)', '[a](<x\\\\\');alert(1);//.md>)']) {
      assert.deepStrictEqual(handlerAttrs(render(src)).map((a) => a.name), [], src);
    }
  });

  test('a relative link still opens the same target', () => {
    // The values the old rewrite passed to openWikilink, for the hrefs it
    // handled. Left column is the markdown; right is what must still arrive.
    // The last two are a deliberate CHANGE, not a preservation, and are here so
    // it is pinned rather than incidental. The old path read the href back out
    // of finished HTML, where marked had URI-encoded it, and delivered
    // `notes/My%20Plan.md` and `r%C3%A9.md`. openWikilink does no decoding, so
    // those matched no file. The destination as written is what opens.
    const cases = [['[a](notes/Plan.md)', 'notes/Plan.md'], ['[a](config.yaml)', 'config.yaml'],
      ['[a](data.json)', 'data.json'], ['[a](log.txt)', 'log.txt'], ['[a](a%20b.md)', 'a%20b.md'],
      ['[a](<notes/My Plan.md>)', 'notes/My Plan.md'], ['[a](<ré.md>)', 'ré.md']];
    for (const [src, expected] of cases) {
      const dom = new JSDOM('<div id="root"></div>', { url: 'http://localhost/' });
      const doc = dom.window.document;
      doc.getElementById('root').innerHTML = render(src);
      const seen = [];
      attachWikilinkHandler(doc, (value) => seen.push(value));
      const anchor = doc.querySelector('a.wikilink');
      assert.ok(anchor, `no wikilink anchor for: ${src}`);
      anchor.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true }));
      assert.deepStrictEqual(seen, [expected], src);
    }
  });

  test('a character reference in a filename stays those characters', () => {
    // The guard against the payload above, seen from the benign side. A
    // destination is written into the attribute escaped as an attribute value,
    // so what the browser decodes back is what the document said, not one
    // decoding further on. Without that, `&#39;` would arrive as a quote, which
    // is exactly how the old rewrite was broken.
    for (const [src, expected] of [['[x](<&#39;.md>)', '&#39;.md'], ['[x](<a&amp;b.md>)', 'a&amp;b.md']]) {
      const dom = new JSDOM('<div id="root"></div>', { url: 'http://localhost/' });
      const doc = dom.window.document;
      doc.getElementById('root').innerHTML = render(src);
      const seen = [];
      attachWikilinkHandler(doc, (value) => seen.push(value));
      doc.querySelector('a.wikilink').dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true }));
      assert.deepStrictEqual(seen, [expected], src);
    }
  });

  test('a link or image title still reaches the attribute, escaped', () => {
    // This renderer writes these attributes itself now, so the title it used to
    // get from the parser for free is its own responsibility.
    const d = new JSDOM(`<div id="root">${render('[x](https://example.com "a \\"quoted\\" title")\n\n![y](https://example.com/i.png "t")')}</div>`).window.document;
    assert.strictEqual(d.querySelector('a').getAttribute('title'), 'a "quoted" title');
    assert.strictEqual(d.querySelector('img').getAttribute('title'), 't');
    assert.strictEqual(d.querySelector('img').getAttribute('alt'), 'y');
  });

  test('an ordinary link keeps its destination exactly as the document wrote it', () => {
    // The same guard as the payload above, on a destination nobody would call
    // hostile, so what the escape does is visible without having to work out
    // how a payload is classified first.
    //
    // marked's own link renderer escapes an href in a mode that leaves an
    // existing character reference intact, which is correct for a URL and wrong
    // once the reference is the attack. Writing the attribute here means the
    // browser decodes back to the characters the document actually wrote:
    // `&amp;` stays `&amp;` rather than becoming a bare ampersand.
    for (const [src, expected] of [
      ['[a](https://example.com/?a=1&amp;b=2)', 'https://example.com/?a=1&amp;b=2'],
      ['[a](<https://example.com/?q=&quot;x>)', 'https://example.com/?q=&quot;x'],
    ]) {
      const d = new JSDOM(`<div id="root">${render(src)}</div>`).window.document;
      const anchor = d.querySelector('a');
      assert.ok(anchor, `no anchor for: ${src}`);
      assert.strictEqual(anchor.getAttribute('href'), expected, src);
    }
  });

  test('links the rewrite never claimed are still ordinary links', () => {
    for (const [src, href] of [['[a](https://example.com/x.md)', 'https://example.com/x.md'],
      ['[a](mailto:x@example.com)', 'mailto:x@example.com'], ['[a](page.html)', 'page.html']]) {
      const d = new JSDOM(`<div id="root">${render(src)}</div>`).window.document;
      const anchor = d.querySelector('a');
      assert.strictEqual(anchor.getAttribute('href'), href, src);
      assert.strictEqual(anchor.getAttribute('class'), null, src);
    }
  });
});

// ---------------------------------------------------------------------------
// Highlights and tags: the last two source rewrites.
//
// `==text==` and `#tag` were regexes over the whole document that spliced
// <mark> and <span class="md-tag"> into the markdown. They are not an injection
// point on their own, but they are why the raw-HTML decision could not be made:
// once agent HTML stops being trusted, HTML the renderer wrote into the source
// is indistinguishable from HTML the document's author wrote there. Both are
// tokenizers now, which also fixes what a whole-document regex could never get
// right.
// ---------------------------------------------------------------------------
describe('renderMarkdown: highlights and tags stay out of code', () => {
  const doc = (html) => new JSDOM(`<div id="root">${html}</div>`).window.document;

  test('a fenced block containing #tag or ==text== keeps its own text', () => {
    // Before: the regexes ran inside the fence, so the block rendered visible
    // span and mark tags, and highlight.js then detected the block as HTML.
    const code = doc(render('```\nlet a = 1; // #todo and ==x==\n```\n')).querySelector('pre code');
    assert.strictEqual(code.textContent, 'let a = 1; // #todo and ==x==');
    assert.strictEqual(code.querySelectorAll('.md-tag, mark').length, 0);
  });

  test('a tag at the start of a line no longer swallows the line break', () => {
    // Before: the pattern consumed the preceding whitespace, newline included,
    // and put a single space back, so the two lines ran together.
    const d = doc(render('line one\n#tag next\n'));
    assert.ok(d.querySelector('br'), 'the line break survives');
    assert.strictEqual(d.querySelector('.md-tag').textContent, '#tag');
  });

  test('a tag renders after any inline construct, not only after plain prose', () => {
    // A tag is offered its position by whatever precedes it. After an inline
    // token the remaining source begins with the separating space, so a
    // tokenizer anchored at `#` alone never matches and the tag silently
    // becomes prose. The whole-document regex this replaced had no such blind
    // spot, and every one of these rendered a tag before this work.
    const cases = [
      ['**done** #project', 'strong'],
      ['*soon* #later', 'em'],
      ['`code` #snippet', 'code'],
      ['[[Roadmap]] #plan', 'a.wikilink'],
      ['[External](https://example.com/a) #link', 'a'],
      ['==marked== #done', 'mark'],
      ['plain prose #after', null],
    ];
    for (const [src, preceding] of cases) {
      const d = new JSDOM(`<div id="root">${render(src)}</div>`).window.document;
      const tag = d.querySelector('.md-tag');
      assert.ok(tag, `no tag rendered for: ${src}`);
      assert.match(tag.textContent, /^#/, src);
      if (preceding) assert.ok(d.querySelector(preceding), `the construct before it was lost: ${src}`);
      // The separating space must survive: the tag reads as a separate word.
      assert.match(d.getElementById('root').textContent, / #/, `space lost before the tag: ${src}`);
    }
  });

  test('a hash inside a word is still not a tag', () => {
    for (const src of ['C#programming is fine', 'issue#42 stays', 'a#b stays']) {
      const d = new JSDOM(`<div id="root">${render(src)}</div>`).window.document;
      assert.strictEqual(d.querySelectorAll('.md-tag').length, 0, src);
    }
  });

  test('the ordinary forms render exactly as they did', () => {
    assert.strictEqual(render('a #tag b'), '<p>a <span class="md-tag">#tag</span> b</p>\n');
    assert.strictEqual(render('a ==hi== b'), '<p>a <mark>hi</mark> b</p>\n');
    assert.strictEqual(render('a==b==c'), '<p>a<mark>b</mark>c</p>\n');
    assert.strictEqual(render('C#programming is fine'), '<p>C#programming is fine</p>\n');
    assert.strictEqual(render('x `#tag` y'), '<p>x <code>#tag</code> y</p>\n');
  });
});

// ---------------------------------------------------------------------------
// Injection point 1: raw HTML reaching innerHTML.
//
// marked passes HTML through by design in its current major, and this renderer
// assigns the result to innerHTML with nothing in between. Recorded payloads,
// run against the previous renderer:
//   <img src=x onerror=alert(1)>   -> the same bytes, verbatim, into the DOM
//   Text <script>alert(1)</script> -> the same bytes, verbatim, into the DOM
// The script element is inert when set through innerHTML, which is a property
// of that one tag and not a defence; the image handler fires on render, with no
// interaction at all.
//
// And a FIFTH point, named by neither the card nor the criteria, found while
// closing this one: marked applies no scheme filter to a link destination.
//   [click](javascript:alert(1)) -> <a href="javascript:alert(1)">click</a>
// which runs on click. Same class, same renderer, same release.
// ---------------------------------------------------------------------------
describe('renderMarkdown: markdown cannot carry HTML into the page', () => {
  // Query from #root, never from the document: the wrapper is a div, and
  // counting it would report every payload as having produced one.
  const doc = (html) => new JSDOM(`<div id="root">${html}</div>`, { url: 'http://localhost/' })
    .window.document.getElementById('root');
  const handlerNames = (root) => Array.from(root.querySelectorAll('*'))
    .flatMap((el) => Array.from(el.attributes).map((a) => a.name)).filter((n) => n.startsWith('on'));

  test('a tag written in the document becomes text, not an element', () => {
    const payloads = [
      ['<img src=x onerror=alert(1)>', 'img'],
      ['Text <script>alert(1)</script> more', 'script'],
      ['<div onmouseover="alert(1)">hover</div>', 'div'],
      ['<svg onload="alert(1)"></svg>', 'svg'],
      ['<iframe src="javascript:alert(1)"></iframe>', 'iframe'],
      ['<a href="javascript:alert(1)">x</a>', 'a'],
      ['<style>*{x:y}</style>', 'style'],
      ['> [!note] fine\n> <img src=x onerror=alert(1)>\n', 'img'],
      ['| a |\n| --- |\n| <img src=x onerror=alert(1)> |\n', 'img'],
      ['- <img src=x onerror=alert(1)>\n', 'img'],
      ['[[Note|<img src=x onerror=alert(1)>]]', 'img'],
    ];
    for (const [src, tag] of payloads) {
      const d = doc(render(src));
      assert.strictEqual(d.querySelectorAll(tag).length, 0, `${tag} element created by: ${src}`);
      assert.deepStrictEqual(handlerNames(d), [], `handler attribute created by: ${src}`);
    }
  });

  test('the escaped tag is still legible to the reader', () => {
    assert.match(doc(render('<img src=x onerror=alert(1)>')).textContent, /<img src=x onerror=alert\(1\)>/);
  });

  test('a script scheme cannot reach an href or a src', () => {
    for (const src of ['[click](javascript:alert(1))', '[click](JaVaScRiPt:alert(1))',
      '[x](vbscript:msgbox)', '[x](data:text/html;base64,PHN2Zz4=)',
      '![x](javascript:alert(1))', '[x](java&Tab;script:alert(1))', '[x](&#106;avascript:alert(1))']) {
      // The RESOLVED url, which is what the browser would act on: a relative
      // href against the page's origin comes back as http:, and only a
      // destination that really carries a scheme keeps one of its own.
      for (const el of doc(render(src)).querySelectorAll('a[href], img[src]')) {
        const resolved = new URL(el.href || el.src, 'http://localhost/');
        assert.ok(['http:', 'https:', 'mailto:'].includes(resolved.protocol),
          `${resolved.protocol} survived in ${el.outerHTML} from: ${src}`);
      }
    }
  });

  test('the link text of a blocked destination is still shown', () => {
    assert.match(doc(render('[click me](javascript:alert(1))')).textContent, /click me/);
  });

  test('a hostile image alt or title cannot become an attribute', () => {
    // The image renderer writes src, alt and title itself, so each is a value
    // this file escapes rather than one the parser escapes for it.
    for (const src of [
      '![a" onerror="alert(1)](https://example.com/i.png)',
      '![ok](https://example.com/i.png "t" onload="alert(1)")',
      '![ok](https://example.com/i.png \'a" onerror="alert(1)\')',
    ]) {
      const d = doc(render(src));
      assert.deepStrictEqual(handlerNames(d), [], `handler attribute from: ${src}`);
      const img = d.querySelector('img');
      if (img) {
        // The alt legitimately CONTAINS the characters `onerror=`: that is the
        // point. What must not exist is an attribute of that name, which the
        // sweep above covers, and the destination must be untouched by it.
        assert.strictEqual(img.getAttribute('src'), 'https://example.com/i.png', src);
        const names = Array.from(img.attributes).map((a) => a.name).sort();
        assert.ok(names.every((n) => ['src', 'alt', 'title'].includes(n)),
          `unexpected attribute ${names.join(',')} from: ${src}`);
      }
    }
  });

  test('an image alt and title round-trip the characters the document wrote', () => {
    const img = doc(render('![a "quoted" b](https://example.com/i.png "t \'x\' u")')).querySelector('img');
    assert.strictEqual(img.getAttribute('alt'), 'a "quoted" b');
    assert.strictEqual(img.getAttribute('title'), "t 'x' u");
  });

  test('an HTML comment stays invisible instead of becoming visible text', () => {
    // Not decoration: the streaming path renders the raw response text, which
    // carries Rundock's own <!-- RUNDOCK:... --> markers. Escaping a comment
    // would have printed those markers into the conversation.
    assert.strictEqual(render('<!-- RUNDOCK:COMPLETE -->'), '');
    assert.strictEqual(doc(render('a <!-- x --> b')).textContent.trim(), 'a  b');
  });
});

// ---------------------------------------------------------------------------
// The other inline handler this renderer wrote. Not an injection point: the
// attribute is a constant and nothing from the document reaches it. It is here
// because a Content-Security-Policy worth having forbids inline handlers, and
// every one that survives is one more reason a policy cannot be turned on.
// ---------------------------------------------------------------------------
describe('renderMarkdown: the copy button is a listener, not an attribute', () => {
  const mount = (html) => {
    const dom = new JSDOM('<div id="root"></div>', { url: 'http://localhost/' });
    dom.window.document.getElementById('root').innerHTML = html;
    return dom;
  };

  test('a rendered code block carries no event-handler attribute', () => {
    const dom = mount(render('```js\nconst x = 1;\n```\n'));
    const names = Array.from(dom.window.document.querySelectorAll('*'))
      .flatMap((el) => Array.from(el.attributes).map((a) => a.name));
    assert.ok(!names.some((n) => n.startsWith('on')), render('```js\nconst x = 1;\n```\n'));
  });

  test('clicking the button still copies the code block text', () => {
    const dom = mount(render('```js\nconst x = 1;\nconsole.log(x);\n```\n'));
    const copied = [];
    Object.defineProperty(dom.window.navigator, 'clipboard', {
      configurable: true,
      value: { writeText: (text) => { copied.push(text); return Promise.resolve(); } },
    });
    attachCodeCopyHandler(dom.window.document);
    const button = dom.window.document.querySelector('.copy-code-btn');
    assert.ok(button, 'the button is rendered');
    button.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true }));
    assert.deepStrictEqual(copied, ['const x = 1;\nconsole.log(x);']);
  });
});

test('markdown-render.js is the only client script that drives marked', () => {
  // The renderer used to configure the SHARED `marked` global: setOptions for
  // gfm and breaks, plus the code and list renderer overrides. It now builds a
  // private instance, which is the right shape and quietly changes what any
  // other caller would get. A second caller doing `marked.parse(...)` would
  // still work, and would silently lose line breaks, code highlighting and the
  // empty-ordered-list fix, with nothing to notice.
  //
  // There is no such caller today. This is what says so, and what fails if one
  // arrives: route it through RundockMarkdown rather than the global.
  const publicDir = path.join(__dirname, '..', '..', 'public');
  const owner = path.join(publicDir, 'markdown-render.js');
  const scripts = [];
  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.name === 'vendor' || entry.name === 'node_modules') continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.name.endsWith('.js') && !entry.name.endsWith('.min.js')) scripts.push(full);
    }
  };
  walk(publicDir);
  assert.ok(scripts.length >= 15, `sanity: scanned ${scripts.length} client scripts`);
  assert.ok(scripts.includes(owner), 'sanity: the owning module is in scope');

  const offenders = scripts
    .filter((file) => file !== owner)
    .filter((file) => /\bmarked\s*\.\s*(parse|parseInline|use|setOptions|lexer)\b/.test(fs.readFileSync(file, 'utf-8')))
    .map((file) => path.relative(publicDir, file));
  assert.deepStrictEqual(offenders, [],
    'these drive marked directly and would not get this renderer\'s options or overrides');
});

describe('renderMarkdown: escaping a raw block does not reach rendered HTML', () => {
  // The raw-block guard keys off marked's `escaped` flag, which the tokenizer
  // sets on text it produced while inside <pre>/<code>/<kbd>/<script>. The flag
  // is cleared before parsing rather than acted on at render time, so it can
  // only ever affect tokens the LEXER made. A renderer-level override would
  // also see any token the PARSER synthesises, and marked has historically
  // built loose list items and task checkboxes by wrapping already-rendered
  // HTML in a text token. Escaping one of those would turn a document's own
  // formatting into visible tags.
  //
  // These shapes are the ones that would show it. They are in the benign
  // fixture too; they are here as well so the failure names itself.
  const root = (src) => new JSDOM(`<div id="root">${render(src)}</div>`)
    .window.document.getElementById('root');

  test('a loose list keeps its formatting and renders an ampersand once', () => {
    const el = root('- a\n\n- **b** & c\n');
    assert.ok(el.querySelector('li p strong'), 'the strong element survives');
    assert.strictEqual(el.querySelector('li p strong').textContent, 'b');
    assert.match(el.textContent, /b & c/, 'one ampersand, not an escaped entity');
    assert.ok(!el.innerHTML.includes('&amp;amp;'), 'the ampersand is not double-encoded');
    assert.ok(!el.textContent.includes('<strong>'), 'no visible tags');
  });

  test('a loose task list keeps its checkboxes', () => {
    const el = root('- [ ] a\n\n- [x] b\n');
    const boxes = el.querySelectorAll('input[type="checkbox"]');
    assert.strictEqual(boxes.length, 2, 'both checkboxes are real elements');
    assert.strictEqual(el.querySelectorAll('input[checked]').length, 1);
    assert.ok(!el.textContent.includes('<input'), 'no visible input markup');
  });

  test('a loose list item keeps a link as an element', () => {
    const el = root('- one\n\n- two [a link](https://example.com/b) and [[Roadmap|an alias]]\n');
    assert.strictEqual(el.querySelector('li p a[href]').getAttribute('href'), 'https://example.com/b');
    assert.strictEqual(el.querySelector('li p a.wikilink').getAttribute('data-wikilink'), 'Roadmap');
  });
});

describe('renderMarkdown: the fallbacks still behave', () => {
  test('a code block renders escaped text when language resolution throws', () => {
    // The catch around resolveCodeLanguage. Highlighting is a nicety and the
    // block still has to render, with its content escaped rather than raw.
    const { renderMarkdown: renderWithBrokenHighlighter } = createMarkdownRenderer({
      marked: loadBrowserMarked(),
      resolveCodeLanguage: () => { throw new Error('highlighter unavailable'); },
    });
    const html = renderWithBrokenHighlighter('```js\n<img src=x onerror=alert(1)>\n```\n', {});
    const root = new JSDOM(`<div id="root">${html}</div>`).window.document.getElementById('root');
    assert.strictEqual(root.querySelectorAll('img').length, 0, 'the fallback escapes too');
    assert.strictEqual(root.querySelector('pre code').textContent, '<img src=x onerror=alert(1)>');
    assert.strictEqual(root.querySelector('.code-lang').textContent, 'js');
  });

  test('an unterminated comment leaves the text before it intact', () => {
    // The header records what a marker still arriving looks like: it shows as
    // text for a frame instead of swallowing the rest of the message, which is
    // what an unterminated comment assigned to innerHTML used to do. Both
    // halves of that claim are asserted here so neither can regress quietly.
    const root = new JSDOM(`<div id="root">${render('Done. <!-- RUNDOCK:COMP')}</div>`)
      .window.document.getElementById('root');
    assert.match(root.textContent, /Done\./, 'the text before the opener survives');
    assert.match(root.textContent, /<!-- RUNDOCK:COMP/, 'the partial marker reads as characters');
    assert.strictEqual(root.querySelectorAll('img, svg, iframe, script').length, 0);
    assert.deepStrictEqual(Array.from(root.querySelectorAll('*'))
      .flatMap((el) => Array.from(el.attributes).map((a) => a.name)).filter((n) => n.startsWith('on')), []);
  });

  test('the callouts option still turns callouts off, and the next render back on', () => {
    // The one stateful mechanism the extension rewrite introduced: the per-call
    // option is bridged to a per-instance tokenizer by a flag. A flag that
    // failed to reset would leak one render's option into the next.
    const src = '> [!note] Title\n> Body.\n';
    const off = new JSDOM(`<div id="root">${renderMarkdown(src, { callouts: false })}</div>`)
      .window.document.getElementById('root');
    assert.strictEqual(off.querySelectorAll('.callout').length, 0, 'callouts off');
    assert.match(off.textContent, /Body\./, 'the content is still rendered, as a quote');

    const on = new JSDOM(`<div id="root">${renderMarkdown(src)}</div>`)
      .window.document.getElementById('root');
    assert.strictEqual(on.querySelectorAll('.callout').length, 1, 'the flag reset for the next render');
  });

  test('copying without a clipboard api does not throw', () => {
    // Rundock served over plain http from a VPS has no navigator.clipboard, and
    // the textarea fallback needs execCommand, which not every context has
    // either. Failing to copy is acceptable; throwing into the click handler is
    // not.
    const dom = new JSDOM('<div id="root"></div>', { url: 'http://localhost/' });
    dom.window.document.getElementById('root').innerHTML = render('```\nplain\n```\n');
    attachCodeCopyHandler(dom.window.document);
    const button = dom.window.document.querySelector('.copy-code-btn');
    assert.doesNotThrow(() => button.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true })));
  });
});

// ---------------------------------------------------------------------------
// Injection point 1, second door: marked's raw-block text.
//
// Escaping the `html` token closes only the markup marked's own tag regex
// recognises. Its inline tag tokenizer also keeps state: seeing an opening
// <pre>, <code>, <kbd> or <script> sets `lexer.state.inRawBlock`, and every
// text token created while that is set carries `escaped: true`, which tells the
// default text renderer to emit the characters verbatim until the close tag.
//
// So a tag shape the browser accepts but that regex rejects never becomes an
// html token at all. It falls through as text, and the flag hands it to
// innerHTML raw. The wrapper is escaped and the payload inside it is not:
//
//   x <code><img/src=x onerror=alert(1)></code>
//     -> <p>x &lt;code&gt;<img/src=x onerror=alert(1)>&lt;/code&gt;</p>
//
// which is a live image element with a handler that fires on render. The `/`
// before the attribute name is what the regex rejects and the browser does not
// mind. Every raw-block opener works, and <svg/onload=...> works the same way.
describe('renderMarkdown: a raw block is not a way out of escaping', () => {
  const root = (html) => {
    const doc = new JSDOM('<div id="root"></div>', { url: 'http://localhost/' }).window.document;
    doc.getElementById('root').innerHTML = html;
    return doc.getElementById('root');
  };
  const handlerNames = (el) => Array.from(el.querySelectorAll('*'))
    .flatMap((node) => Array.from(node.attributes).map((a) => a.name)).filter((n) => n.startsWith('on'));

  test('a tag marked rejects and the browser accepts cannot survive a raw block', () => {
    const payloads = [
      'x <code><img/src=x onerror=alert(1)></code>',
      'x <kbd><img/src=x onerror=alert(1)></kbd>',
      'x <pre><img/src=x onerror=alert(1)></pre>',
      'x <script><img/src=x onerror=alert(1)></script>',
      'x <code><img src="x" onerror="alert(1)"\'></code>',
      'x <code><svg/onload=alert(1)></code>',
      // A near miss, kept because it looks like the one above and is not. With
      // a second slash the browser reads `src="x/onerror=alert(1)"` as a single
      // unquoted attribute value, since nothing terminates it, so an element is
      // created but no handler. Still markup the document controls, so it is
      // held to the same assertion as the rest.
      'x <code><img/src=x/onerror=alert(1)></code>',
    ];
    for (const src of payloads) {
      const el = root(render(src));
      assert.deepStrictEqual(handlerNames(el), [], `handler attribute survived: ${src}`);
      assert.strictEqual(el.querySelectorAll('img, svg, iframe, script, style').length, 0,
        `element created from document text by: ${src}`);
    }
  });

  test('the escaped payload is legible as characters', () => {
    const text = root(render('x <code><img/src=x onerror=alert(1)></code>')).textContent;
    assert.match(text, /<img\/src=x onerror=alert\(1\)>/);
    assert.match(text, /<code>/, 'the wrapper reads as text too');
  });

  test('a raw block does not change how ordinary text around it is escaped', () => {
    // The fix must not double-escape: marked holds the raw capture in the token
    // and escapes at render, so an entity already written in the prose has to
    // survive as the one character it names.
    assert.strictEqual(render('a &amp; b'), '<p>a &amp; b</p>\n');
    assert.strictEqual(render('5 &lt; 6 and "quoted"'), '<p>5 &lt; 6 and &quot;quoted&quot;</p>\n');
  });
});
